apiVersion: apps/v1
kind: Deployment
metadata:
  name: vehicle-web-app
spec: 
  replicas: 1
  selector: 
    marchLabels: 
      app: vehicle-web-app
  template:
    metadata:
      labels:
        app: vehicle-web-app
    spec:
      containers:
        - name: vehicle-web-app
          image: akscr01sample.azurecr.io/vehicle-web-app:latest
          port:
          - containet_port: 7066
      imagePullSecrets:
        - name: acr-secret
---

apiVersion: v1
kind: Service
metadata: 
  name: vehicle-web-app-service
spec:
  selector: 
    app: vehicle-web-app
  ports:
    - port: 80
      targetPort: 7066
  type: LoadBalancer