apiVersion: apps/v1
kind: Deployment
metadata:
  name: vehicle-web-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vehicle-web-api
  template:
    metadata:
      labels:
        app: vehicle-web-api
    spec:
      containers:
        - name: vehicle-web-api
          image: akscr01sample.azurecr.io/vehicle-web-api:latest
          ports:
            - containerPort: 7095
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: "Production"
            - name: ConnectionStrings__Default
              value: "Server=tcp:sqldbserver8199.database.windows.net,1433;Initial Catalog=ASP_NET_Database;Persist Security Info=False;User ID=Pasupathikumar;Password=NewPassword1234;MultipleActiveResultSets=False;Encrypt=True;TrustServerCertificate=False;Connection Timeout=30;"
          resources:
            requests:
              memory: "512Mi"
              cpu: "500m"
            limits:
              memory: "1Gi"
              cpu: "1"
          readinessProbe:
            httpGet:
              path: /swagger/index.html
              port: 7095
            initialDelaySeconds: 10
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /swagger/index.html
              port: 7095
            initialDelaySeconds: 15
            periodSeconds: 20
      imagePullSecrets:
        - name: acr-secret

---

apiVersion: v1
kind: Service
metadata:
  name: vehicle-web-api-service
spec:
  selector:
    app: vehicle-web-api
  ports:
    - port: 7095
      targetPort: 7095
  type: LoadBalancer

---

apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-specific-ingress
  namespace: default  # Use the appropriate namespace
spec:
  podSelector:
    matchLabels:
      app: vehicle-web-api  # Apply this policy to pods labeled with app=vehicle-web-api
  ingress:
    - from:
        - podSelector:
            matchLabels:
              app: vehicle-web-app  # Only allow traffic from pods with label app=vehicle-web-app
      ports:
        - protocol: TCP
          port: 7095  # Allow traffic on port 7095 (HTTP API)
  egress:
    - to:
        - podSelector: {}
      ports:
        - protocol: TCP
          port: 7095  # Allow egress traffic to port 80
