apiVersion: apps/v1
kind: Deployment
metadata:
  name: vehicle-web-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vehicle-web-api
  template:
    metadata:
      labels:
        app: vehicle-web-api
    spec:
      containers:
        - name: vehicle-web-api
          image: akscr01sample.azurecr.io/vehicle-web-api:latest
          ports:
            - containerPort: 7095
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: "Production"
            - name: ASPNETCORE_URLS
              value: "http://+:7095"
            - name: Jwt__Key
              value: "ab56ufuifywduwd76rGiri7H6uyfivbiNIOUGIUFriouhioud9p9"
            - name: ConnectionStrings__Default
              value: "Server=tcp:sqldbserver8199.database.windows.net,1433;Initial Catalog=ASP_NET_Database;Persist Security Info=False;User ID=Pasupathikumar;Password=NewPassword1234;MultipleActiveResultSets=False;Encrypt=True;TrustServerCertificate=False;Connection Timeout=30;"  
      imagePullSecrets:
        - name: acr-secret

---

apiVersion: v1
kind: Service
metadata:
  name: vehicle-web-api-service
spec:
  selector:
    app: vehicle-web-api
  ports:
    - port: 7095
      targetPort: 7095
  type: LoadBalancer

