apiVersion: apps/v1
kind: Deployment
metadata:
  name: vehicle-web-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vehicle-web-api
  template:
    metadata:
      labels:
        app: vehicle-web-api
    spec:
      containers:
        - name: vehicle-web-api
          image: akscr01sample.azurecr.io/vehicle-web-api:latest
          ports:
            - containerPort: 7095
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: "Production"
            - name: ConnectionStrings__DefaultConnection
              valueFrom:
                secretKeyRef:
                  name: db-connection-string
                  key: DefaultConnection
          resources:
            requests:
              memory: "512Mi"
              cpu: "500m"
            limits:
              memory: "1Gi"
              cpu: "1"
          readinessProbe:
            httpGet:
              path: /health
              port: 7095
            initialDelaySeconds: 10
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /health
              port: 7095
            initialDelaySeconds: 15
            periodSeconds: 20
      imagePullSecrets:
        - name: acr-secret

---

apiVersion: v1
kind: Service
metadata:
  name: vehicle-web-api-service
spec:
  selector:
    app: vehicle-web-api
  ports:
    - port: 80
      targetPort: 7095
  type: LoadBalancer